baseURL = "https://ronnyshan.github.io/"
title = "Jing Shan's Blog"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
disqusShortname = "" # Add your Disqus shortname if you have one
googleAnalytics = "" # Add your Google Analytics ID if you have one
preserveTaxonomyNames = true
paginate = 5
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  header_image = "img/home-bg-jeep.jpg"
  SEOTitle = "Jing Shan's Blog"
  description = "Jing Shan's personal blog, sharing insights and experiences."
  keyword = "Jing Shan, blog, personal website, technology, programming"
  slogan = "Exploring the World, One Step at a Time"
  upstreamAttribution = true

  image_404 = "img/404-bg.jpg"
  title_404 = "You have reached an empty space :("
  omit_categories = false

  page_view_counter = false
  leancloud_app_id = ""
  leancloud_app_key = ""

  algolia_search = true
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  sidebar_about_description = "Software Developer, Open Source Enthusiast, and Life Adventurer"
  sidebar_avatar = "img/your-avatar.jpg"

  featured_tags = true
  featured_condition_size = 1

  ba_track_id = ""

  disqus_proxy = ""
  disqus_site = ""

  twikoo_env_id = ""

  # Enable wechat pay & alipay to allow readers to send reward money if they like the articles
